### ISSUE TITLE
Texture baking is broken in Blender 4.3.2

### ISSUE THREAD

**Issue by Zirenow** [SavMartin/TexTools-Blender#252]
Trying to bake either "Emission" or "Base Color" crashes the addon and returns black texture

Error message:

```
Python: Traceback (most recent call last):
  File "/home/(my name)/.config/blender/4.3/scripts/addons/TexTools_1_6_1/op_bake.py", line 474, in bake
    assign_tune_materials(obj, setup_bake_nodes=True)
  File "/home/(my name)/.config/blender/4.3/scripts/addons/TexTools_1_6_1/op_bake.py", line 409, in assign_tune_materials
    channel_ignore(modes['emission_strength'].relink['n'], slot.material)
  File "/home/(my name)/.config/blender/4.3/scripts/addons/TexTools_1_6_1/op_bake.py", line 955, in channel_ignore
    bsdf_node.inputs[channel].default_value = 1.0
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

ValueError: bpy_struct: item.attr = val: sequence expected at dimension 1, not 'float'

```

**Comment by ndahn** [comment]
Works when using the version from the master branch!
